language: python

matrix:
  include:

    - os: linux
      python: 3.5
      name: ubuntu 16.04 - python@3.5
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.6
      name: ubuntu 16.04 - python@3.6
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 16.04 - python@3.7
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8
      name: ubuntu 16.04 - python@3.8
      dist: xenial
      sudo: true
      env:
        - MATRIX_EVAL=""


before_install:
  - travis_retry eval "${MATRIX_EVAL}"
    #- pip install -r requirements.txt
  - python -m pip install --upgrade pip
  - python -m pip --version

  - python -m pip install wheel
  - python -m pip install numpy==1.17
  - python -m pip install scipy>=1.2.1
  - python -m pip install scikit-learn>=0.20.3
  - python -m pip install pydicom==1.3.0
  - python -m pip install pandas==0.25.3
  - python -m pip install opencv-python
  - python -m pip install tqdm
  - python -m pip install itk

  # testing libraries
  - python -m pip install pytest==3.0.7
  - python -m pip install hypothesis>=4.13.0
  - python -m pip install codecov
  - python -m pip install pytest-cov

install:
  - python setup.py install

script:
  - travis_wait 45 python -m pytest --cov=CTLungSeg --cov-config=.coveragerc

after_succes:
  - codecov
