version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
platform: x64

clone_folder: c:\projects\segmentation

environment:

  WORKSPACE: C:\projects

  matrix:

  - PYTHON: "C:\\Python35-x64"
    VERSION: 35
    ARCH: x64

  - PYTHON: "C:\\Python36-x64"
    VERSION: 36
    ARCH: x64

  - PYTHON: "C:\\Python37-x64"
    VERSION: 37
    ARCH: x64

  - PYTHON: "C:\\Python38-x64"
    VERSION: 38
    ARCH: x64

build: off

install:
  - "%PYTHON%\\python.exe --version"
  - cd %WORKSPACE%\segmentation
  - "%PYTHON%\\python.exe -m pip install -U pip"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe setup.py install"
