site_name:          COVID-19 Lung Segmentation
repo_url:           https://github.com/RiccardoBiondi/segmentation
site_description:   Scripts for segmentation of lung TAC images


markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - docs/pipeline/lung_extraction.md
  - docs/pipeline/slice_and_ROI.md
  - docs/pipeline/clustering.md
  - docs/pipeline/train.md
  - docs/pipeline/labeling.md
  - docs/segmentation/method.md
  - docs/segmentation/utils.md


theme:              jekyll-theme-slate
