name: Windows CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.cfg}}
    name: ${{matrix.cfg}}
    strategy:
      matrix:
         cfg: [windows-latest]
         python-version: [3.7, 3.8, 3.9, '3.10', '3.11']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up python${{matrix.python-version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install -r requirements.txt

    - name: Install testing dependencies
      run: |
        python -m pip install hypothesis>=4.13.0 codecov pytest-cov
  
    - name: Install segmentation Processing Tools
      run: |
        python setup.py develop --user

    - name: Test with pytest
      run: |
            python -m pytest
